#!/bin/bash
self=$(basename $0)
echo "inside hook: ${self}"
touch /tmp/hook_${self}
#touch /tmp/running
#echo 'before'
#python ${OPENSHIFT_REPO_DIR}/cloudbot.py 2>&1 ${OPENSHIFT_DATA_DIR}/cloudbot.log &
#echo 'after'